### ISSUE TITLE
array_remove

### ISSUE THREAD

**Issue by mooneyme** [gasparesganga/postgis-normalize-geometry#1]
I don't have the `array_remove` function. I am using postgres 9.2.6. I tried to create my own array remove function, but this does not work (see snippet below). Is there any other work around to be able to use the `normalize_geometry()` function without upgrading my postgres?

```
CREATE OR REPLACE FUNCTION public.array_remove(
    a anyarray,
    e anyelement)
  RETURNS anyarray AS
$BODY$
BEGIN
return array(
select x from unnest(a) x where x <> e
);
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION public.array_remove(anyarray, anyelement)
  OWNER TO "server-superusers";
```

**Comment by gasparesganga** [comment]
Your custom `array_remove` function has two issues:
- The `<>` operator will give you an _operator not unique_ error, but we can use the `=` one
- There can be some problems with `NULLs` handling, we can use a workaround

Here are a _SQL_ function and a _PL/pgSQL_ variant which should both work just fine.

**Can you perform some tests and return some feedback, so I will include those in the documentation for other users' benefit?**

``` sql
-- SQL
CREATE OR REPLACE FUNCTION array_remove(
    PAR_array   anyarray, 
    PAR_element anyelement
) RETURNS anyarray AS $$
    SELECT ARRAY(
        SELECT value FROM unnest(PAR_array) AS value 
        WHERE CASE WHEN PAR_element IS null THEN (value IS NOT null) ELSE (NOT value = PAR_element) END
    );
$$ LANGUAGE sql;


-- PL/pgSQL
CREATE OR REPLACE FUNCTION array_remove(
    PAR_array   anyarray, 
    PAR_element anyelement
) RETURNS anyarray AS $$
BEGIN
    RETURN ARRAY(
        SELECT value FROM unnest(PAR_array) AS value 
        WHERE CASE WHEN PAR_element IS null THEN (value IS NOT null) ELSE (NOT value = PAR_element) END
    );
END;
$$ LANGUAGE plpgsql;
```

**Comment by gasparesganga** [comment]
Not that I wasn't expecting some huge thanks, but at least a minimum feedback would have been appreciated...

Anyways, [v1.1.0](https://github.com/gasparesganga/postgis-normalize-geometry/commit/baadb681daf4d67f94a993225474350092e99f10) includes a SQL backport for `array_remove()` which should make this library fully compatible with PostgreSQL 9.2.

Cheers
