### ISSUE TITLE
Fix slivers (Holes) between polygons ( generated after removing spikes)

### ISSUE THREAD

**Issue by lucasmation** [gasparesganga/postgis-normalize-geometry#3]
@gasparesganga, perhaps you are the right person to fix this:

https://gis.stackexchange.com/questions/289717/fix-slivers-holes-between-polygons-generate-after-removing-spikes

**Comment by gasparesganga** [comment]
Hi. This looks like a typical use case for `normalize_geometry` indeed.
Have you tried it? It should work just fine.

PS: Applying `ST_Buffer` like that will change and alterate your geometries. I would not advice to use that.

**Comment by gasparesganga** [comment]
Any news about this?

**Comment by gasparesganga** [comment]
Well, I guess you managed to fix that, I'm closing this.
